name: saucectl cypress tests v1

on:
  pull_request:
  push:
    paths:
      - "v1"
    branches:
      - main
  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  cypress-grep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: v1/examples/cypress-grep/package-lock.json

      - name: Install dependencies
        working-directory: v1/examples/cypress-grep
        run: npm ci

      - name: Cypress with Cypress Grep
        uses: saucelabs/saucectl-run-action@v3
        with:
          working-directory: v1/examples/cypress-grep